ALTER TABLE reports DROP COLUMN IF EXISTS delivery_method;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS download_count INTEGER DEFAULT 0;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS download_token VARCHAR UNIQUE;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS generation_started_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS generation_completed_at TIMESTAMP;
