ALTER TABLE orders ALTER COLUMN status TYPE VARCHAR(50);
UPDATE orders SET status = 'DELIVERED' WHERE status = 'DELIVERED';
ALTER TABLE orders ADD CONSTRAINT check_status 
CHECK (status IN ('PENDING', 'PAID', 'GENERATING', 'DELIVERED', 'GENERATION_FAILED', 'CANCELLED'));
